<?php

use Illuminate\Database\Seeder;

class PublicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		// Joel M. Addawe
        DB::table('publications')->insert([
			[
				'title' => 'Bifurcation analysis of dengue transmission model in Baguio City, Philippines',
				'author' => 'Libatique, CP, Pajimola, AKP and Addawe, JM.',
				'published_date' => '2017-01-01',
				'type' => 'International',
				'journal' => 'AIP Conference Proceedings',
				'volume' => '1905',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Parameter Optimization of differential evolution algorithm for automatic playlist generation problem',
				'author' => 'Alamag, KMNB, and Addawe, JM.',
				'published_date' => '2017-01-01',
				'type' => 'International',
				'journal' => 'AIP Conference Proceedings',
				'volume' => '1905',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Treatment on outliers in UBJ-SARIMA models for forecasting dengue cases on age groups not eligible for vaccination in Baguio City, Philippines',
				'author' => 'Magsakay, CB, De Vera, NU, Libatique, CP, Addawe, RC and Addawe, JM.',
				'published_date' => '2017-01-01',
				'type' => 'International',
				'journal' => 'AIP Conference Proceedings',
				'volume' => '1905',
				'link' => 'https://doi.org/10.1088/1742-6596/893/1/012061',
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Differential evolution-simulated annealing for multiple sequence alignment',
				'author' => 'Addawe, R.C., Addawe, JM., Sueño, M.R.K. and Magadia, J.C.',
				'published_date' => '2017-01-01',
				'type' => 'International',
				'journal' => 'IOP Conf. Series: Journal of Physics: Conference Series',
				'volume' => '893',
				'link' => 'https://doi.org/10.1088/1742-6596/893/1/012061',
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Parameter Optimization of Vertical Decomposition with Genetic Algorithm for Multiple Sequence Alignment',
				'author' => 'Addawe, J. and Gabriel, P.',
				'published_date' => '2017-01-01',
				'type' => 'National',
				'journal' => 'Proceedings of the 17th Philippine Computing Science Congress(PCSC2017)',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Air Pollution Simulation in Baguio City, Philippines Using Genetic Algorithm',
				'author' => 'Javellana, L. and Addawe, J.',
				'published_date' => '2017-01-01',
				'type' => 'National',
				'journal' => 'Proceedings of the 17th Philippine Computing Science Congress(PCSC2017)',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'A mathematical model of transmission of rice tungro disease by Nephotettix Virescens',
				'author' => 'Blas, N., Addawe, J. and David, G.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'AIP Conf. Proc.: AIP Publishing  ( 4th International Conference on Fundamental and Applied Sciences (ICFAS2016)',
				'volume' => '1787',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Alternative Robust Estimators for Autoregressive Models with Outliers Using Differential Evolution Algorithm',
				'author' => 'Addawe, R., Addawe, J. and Magadia, J.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'AIP Conference Proceedings: AIP Publishing.(4th International Conference on Fundamental and Applied Sciences (ICFAS2016) AIP Conf. Proc.',
				'volume' => '1787',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Mathematical Analysis of tuberculosis transmission model with delay',
				'author' => 'Lapaan, R.D., Collera, J.A., and Addawe, J. M.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'AIP Conference Proceedings:AIP Publishing.(4th International Conference on Fundamental and Applied Sciences (ICFAS2016)',
				'volume' => '1787',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Dynamics of Climate-based Malaria Transmission Model with Age-Structured Human Population',
				'author' => 'Addawe, J., and Pajimola, A.K.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'THE 4TH INTERNATIONAL CONFERENCE ON QUANTITATIVE SCIENCES AND ITS APPLICATIONS (ICOQSIA 2016) AIP Conf. Proc.',
				'volume' => '1782',
				'link' => 'https://doi.org/10.1063/1.4966069',
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Optimizing Genetic Algorithm Parameters for Multiple Sequence Alignment Based on Structural Information',
				'author' => 'Sueño M.R. and Addawe J.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'Advanced Studies in Biology',
				'volume' => '8',
				'link' => 'http://dx.doi.org/10.12988/asb.2016.51250',
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'P-adic Qth Roots Via Newton-Raphson Method',
				'author' => 'Ignacio, P.S., Addawe, J., and Nable, J.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'Thai Journal of Mathematics',
				'volume' => '14',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Optimization of seasonal ARIMA models using differential evolution – simulated annealing (DESA) algorithm in forecasting dengue cases in Baguio City',
				'author' => 'Addawe, R., Addawe, J. and Magadia, J.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'AIP Conf. Proc.',
				'volume' => '1776',
				'link' => 'http://dx.doi.org/10.1063/1.4965385',
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Analysis of age-structured malaria transmission model',
				'author' => 'Addawe, J. and Lope, E.',
				'published_date' => '2012-01-01',
				'type' => 'National',
				'journal' => 'Philippine Science Letters',
				'volume' => '5',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Sensitivity analysis of age-structured malaria transmission model',
				'author' => 'Addawe, J. and Lope, E.',
				'published_date' => '2012-01-01',
				'type' => 'International',
				'journal' => 'AIP Conf. Proc.',
				'volume' => '1482',
				'link' => 'http://dx.doi.org/10.1063/1.4757437',
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'DESA: A Hybrid Optimization Algorithm for High Dimensional Functions',
				'author' => 'Addawe, R., Addawe, J, Adorio, E and Magadia, J.',
				'published_date' => '2006-05-01',
				'type' => 'International',
				'journal' => 'A publication of the International Association of Science and Technology for Development (IASTED), Proceedings of the International Conference on Control and Applications',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'A DESA Algorithm for Parameter Estimation of Gaussians',
				'author' => 'Addawe, R., Addawe, J., Adorio, E. and Magadia, J.',
				'published_date' => '2005-05-01',
				'type' => 'National',
				'journal' => 'Proceedings of the 5th Philippine Computing Science Congress',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Building Stone Walls: A Case Study from the Philippines',
				'author' => 'Alangui, W.',
				'published_date' => NULL,
				'type' => 'International',
				'journal' => 'Numeracy as a Social Practice: Global and Local Perspectives',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Forest of the Lost Child, Dus Ailal & Dahas: Recognizing Indigenous Peoples’ Traditional Knowledge in Forest Management as Means for Climate Change Adaptation and Mitigation',
				'author' => 'Alangui, W. et. al.',
				'published_date' => NULL,
				'type' => 'International',
				'journal' => 'Indigenous Knowledge and Climate Change: Foundations for Assessment and Adaptation',
				'volume' => '',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Ethnomathematics and Culturally Relevant Mathematics Education in the Philippines',
				'author' => 'Alangui, W.',
				'published_date' => '2017-01-01',
				'type' => 'International',
				'journal' => 'Ethnomathematics and its Diverse Approaches for Mathematics Education',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => NULL,
				'author' => 'Rosa, L. Shirley, ME Gavarette & W. Alangui.',
				'published_date' => '2017-01-01',
				'type' => 'National',
				'journal' => 'Ethnomathematics and its Diverse Approaches for Mathematics Education',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Framing the Ethnomathematical Process',
				'author' => 'Alangui, W.',
				'published_date' => '2016-01-01',
				'type' => 'Local',
				'journal' => ' Hoy, Boy! A Festschrift for Delfin L. Tolentino, Jr.',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Role of Ethnomathematics in Mathematics Education',
				'author' => 'Alangui, W. and Rosa, M.',
				'published_date' => '2016-01-01',
				'type' => 'Local',
				'journal' => 'Current and Future Perspectives of Ethnomathematics as a Program',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Current and Future Perspectives of Ethnomathematics as a Program',
				'author' => 'Rosa, M., Ambrosio, U., Orey, D., Shirley, L., Alangui, W., Palhares, P., & Gavarrete, ME.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => '',
				'volume' => '',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Amorphophallus adamsensis (Araceae), a new species from Ilocos Norte, Philippines',
				'author' => 'L Magtoto, D Mones, K Ballada, C Austria, R Dizon, W Alangui, A Reginaldo, W Galvan, K Dizon and W Hetterscheid',
				'published_date' => '2013-01-01',
				'type' => 'International',
				'journal' => 'Blumea',
				'volume' => '58',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Computation of Square and Cube Roots of p-Adic numbers via Newton Raphson Method',
				'author' => 'Ignacio, P.S., Addawe, J., Alangui, W. & Nable, J.',
				'published_date' => '2013-01-01',
				'type' => 'International',
				'journal' => 'Journal of Mathematics Research',
				'volume' => '5',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Bright lights and Questions: Using Mutual Interrogation',
				'author' => 'Adam, A., Alangui, W., & Barton, B.',
				'published_date' => '2010-01-01',
				'type' => 'International',
				'journal' => 'For the Learning of Mathematics',
				'volume' => '30',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'A Comment on: Rowlands & Carson ‘Where would formal, academic mathematics stand in a curriculum informed by ethnomathematics?’ A critical review',
				'author' => 'Adam, S., Alangui, W, Barton, B.',
				'published_date' => '2003-01-01',
				'type' => 'International',
				'journal' => 'Educational Studies in Mathematics',
				'volume' => '52',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Searching for Mathematical Ideas in Stone Walls',
				'author' => 'Alangui, W.',
				'published_date' => '2003-01-01',
				'type' => 'International',
				'journal' => 'Mathematics Education Research: Innovation, Networking, Opportunity. Proceedings of MERGA',
				'volume' => '26',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'The Mathematics Enhancement Project: The Pilot Phase',
				'author' => 'Alangui, W., Autagavaia, J., Barton, B., Kensington-Miller, B., Lane, J., Paterson, J., Poleki, A. & Van Den Heuvel, A.',
				'published_date' => '2002-01-01',
				'type' => 'International',
				'journal' => 'Proceedings of MERGA',
				'volume' => '25',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'The Mathematics Enhancement Project: A Theoretical Approach to Research and Development',
				'author' => 'Barton, B., Autagavaia, J., Poleki, A. & Alangui, W.',
				'published_date' => '2002-01-01',
				'type' => 'International',
				'journal' => 'Proceedings of the Third International Mathematics Education and Society Conference',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'The Mathematics Enhancement Project: Combining research and development',
				'author' => 'Alangui, W., Autagavaia, J., Barton, B., & Poleki, A.',
				'published_date' => '2001-01-01',
				'type' => 'International',
				'journal' => 'Proceedings of MERGA',
				'volume' => '24',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => NULL,
				'author' => 'Alangui, W., Ichikawa, K., and Takahashi, Y.',
				'published_date' => '2017-01-01',
				'type' => 'International',
				'journal' => 'Proceedings of the IPBES-JBF Sub-regional Dialogue Workshop on Indigenous and Local Knowledge (ILK) for South-East and North-East Asia Sub-region',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Indigenous Learning Systems in Bagnen',
				'author' => 'Alangui, W.',
				'published_date' => '2014-01-01',
				'type' => 'National',
				'journal' => 'IPEd Monograph Series',
				'volume' => '3',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Protecting the Forest: Learning from the Agawa Women of Besao, Mt. Province',
				'author' => 'Alangui, W. & Caguioa, MC.',
				'published_date' => '2013-01-01',
				'type' => 'National',
				'journal' => 'Indigenous Peoples, Forests & REDD Plus: Sustaining and Enhancing Forests through Traditional Resource Management',
				'volume' => '2',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Indigenous Women, Climate Change & Forests',
				'author' => 'Alangui, W., Subido, G. & Tinda-an, R.',
				'published_date' => '2011-01-01',
				'type' => 'National',
				'journal' => NULL,
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Sustaining & enhancing forests through traditional resource management',
				'author' => 'Alangui, W., Subido, G. & Tinda-an, R.',
				'published_date' => '2010-01-01',
				'type' => 'National',
				'journal' => NULL,
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Uri at Kasarian ng Pag-aalsang Tayug',
				'author' => 'Rovillos, R. And Alangui, W.',
				'published_date' => '2000-01-01',
				'type' => 'National',
				'journal' => 'The Journal of History',
				'volume' => '46',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Connecting Indigenous Knowledge of Stone Walling and Water Management with Mathematics and its Implication to Indigenous Peoples\' Education',
				'author' => 'Alangui, W.',
				'published_date' => '2004-01-01',
				'type' => 'International',
				'journal' => 'Proceedings of 4th APRU Doctoral Students\' Conference',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'The Mathematics Enhancement Project: The Pilot Phase',
				'author' => 'Alangui, W., Autagavaia, J., Barton, B., Kensington-Miller, B., Lane, J., Paterson, J., Poleki, A. & Van Den Heuvel, A.',
				'published_date' => '2003-01-01',
				'type' => 'National',
				'journal' => 'The New Zealand Mathematics Magazine',
				'volume' => '40',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'A Methodology for Ethnomathematics',
				'author' => 'Alangui, W., Barton, B.',
				'published_date' => '2002-01-01',
				'type' => 'International',
				'journal' => 'Proceedings of Second International Conference on Ethnomathematics (ICEM2)',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Institutionalising Voluntarism: The University of the Philippines Experience',
				'author' => 'Alangui, W.',
				'published_date' => '2001-01-01',
				'type' => 'National',
				'journal' => 'Good Practices and Innovative Experiences in the South: Citizen Initiatives in Social Services, Popular Education and Human Rights',
				'volume' => '3',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Indigenous Learning Systems in a Kankana-ey Community (Mt. Province)',
				'author' => 'Alangui, W.',
				'published_date' => '1997-01-01',
				'type' => 'National',
				'journal' => NULL,
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'he Algebra of the Weaving Patterns, Gong Music and Kinship System of the Kankana-ey',
				'author' => 'The Faculty of the Discipline of Mathematics, University of the Philippines College Baguio.',
				'published_date' => '1996-01-01',
				'type' => 'National',
				'journal' => NULL,
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Learning from Life: An Ethnographic Study of Functional Literacy in Marginal Philippine Communities',
				'author' => 'Alangui, W., Lenora Fe S. Brawner and Raymundo D. Rovillos.',
				'published_date' => '1994-01-01',
				'type' => 'National',
				'journal' => 'Kala (Ifugao) Site Report',
				'volume' => '4',
				'link' => NULL,
				'user_id' => 5,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'DESA: A Hybrid Optimization Algorithm for High Dimensional Functions',
				'author' => '(Main author)',
				'published_date' => '2006-01-01',
				'type' => 'International',
				'journal' => 'Proceedings of the International Association for Science and Technology Education and Development 8th International Conference on Control and Applications',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 4,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'DESA: Differential Evolution: Simulated Annealing for Fitting Linear Combinations of Gaussians to data',
				'author' => '(Main author)',
				'published_date' => '2006-01-01',
				'type' => 'International',
				'journal' => 'Book Proceedings and CD Proceedings of the 55th Session of the International Statistics Institute (ISI2005)',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 4,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'SOURCE ON PRACTICAL WORK FOR TEACHER TRAINERS: HIGH SCHOOL MATHEMATICS 3 AND 4 (Final Edition)',
				'author' => '(co-author)',
				'published_date' => '1998-10-01',
				'type' => 'International',
				'journal' => NULL,
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 4,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'SOURCE ON PRACTICAL WORK FOR TEACHER TRAINERS: HIGH SCHOOL MATHEMATICS 1 AND 2 (Final Edition)',
				'author' => '(co-author)',
				'published_date' => '1998-10-01',
				'type' => 'International',
				'journal' => NULL,
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 4,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Sourcebook on Practical Work for Teacher Trainers High School Mathematics I & II Volume 1 2000 SMEMDP',
				'author' => '(co-author)',
				'published_date' => '2000-02-01',
				'type' => 'International',
				'journal' => NULL,
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 4,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Sourcebook on Practical Work for Teacher Trainers High School Mathematics III & IV Volume 1 1999 SMEMDP',
				'author' => '(co-author)',
				'published_date' => '1999-12-01',
				'type' => 'International',
				'journal' => NULL,
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 4,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			/* [
				'title' => '',
				'author' => '',
				'published_date' => '',
				'type' => '',
				'journal' => '',
				'volume' => '',
				'link' => '',
				'user_id' => ,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			], */
		]);
    }
}
