<?php

use Illuminate\Database\Seeder;

class PublicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		// Joel M. Addawe
        DB::table('publications')->insert([
			[
				'title' => 'Bifurcation analysis of dengue transmission model in Baguio City, Philippines',
				'author' => 'Libatique, CP, Pajimola, AKP and Addawe, JM.',
				'published_date' => '2017-01-01',
				'type' => 'International',
				'journal' => 'AIP Conference Proceedings',
				'volume' => '1905',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Parameter Optimization of differential evolution algorithm for automatic playlist generation problem',
				'author' => 'Alamag, KMNB, and Addawe, JM.',
				'published_date' => '2017-01-01',
				'type' => 'International',
				'journal' => 'AIP Conference Proceedings',
				'volume' => '1905',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Treatment on outliers in UBJ-SARIMA models for forecasting dengue cases on age groups not eligible for vaccination in Baguio City, Philippines',
				'author' => 'Magsakay, CB, De Vera, NU, Libatique, CP, Addawe, RC and Addawe, JM.',
				'published_date' => '2017-01-01',
				'type' => 'International',
				'journal' => 'AIP Conference Proceedings',
				'volume' => '1905',
				'link' => 'https://doi.org/10.1088/1742-6596/893/1/012061',
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Differential evolution-simulated annealing for multiple sequence alignment',
				'author' => 'Addawe, R.C., Addawe, JM., Sueño, M.R.K. and Magadia, J.C.',
				'published_date' => '2017-01-01',
				'type' => 'International',
				'journal' => 'IOP Conf. Series: Journal of Physics: Conference Series',
				'volume' => '893',
				'link' => 'https://doi.org/10.1088/1742-6596/893/1/012061',
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Parameter Optimization of Vertical Decomposition with Genetic Algorithm for Multiple Sequence Alignment',
				'author' => 'Addawe, J. and Gabriel, P.',
				'published_date' => '2017-01-01',
				'type' => 'National',
				'journal' => 'Proceedings of the 17th Philippine Computing Science Congress(PCSC2017)',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Air Pollution Simulation in Baguio City, Philippines Using Genetic Algorithm',
				'author' => 'Javellana, L. and Addawe, J.',
				'published_date' => '2017-01-01',
				'type' => 'National',
				'journal' => 'Proceedings of the 17th Philippine Computing Science Congress(PCSC2017)',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'A mathematical model of transmission of rice tungro disease by Nephotettix Virescens',
				'author' => 'Blas, N., Addawe, J. and David, G.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'AIP Conf. Proc.: AIP Publishing  ( 4th International Conference on Fundamental and Applied Sciences (ICFAS2016)',
				'volume' => '1787',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Alternative Robust Estimators for Autoregressive Models with Outliers Using Differential Evolution Algorithm',
				'author' => 'Addawe, R., Addawe, J. and Magadia, J.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'AIP Conference Proceedings: AIP Publishing.(4th International Conference on Fundamental and Applied Sciences (ICFAS2016) AIP Conf. Proc.',
				'volume' => '1787',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Mathematical Analysis of tuberculosis transmission model with delay',
				'author' => 'Lapaan, R.D., Collera, J.A., and Addawe, J. M.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'AIP Conference Proceedings:AIP Publishing.(4th International Conference on Fundamental and Applied Sciences (ICFAS2016)',
				'volume' => '1787',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Dynamics of Climate-based Malaria Transmission Model with Age-Structured Human Population',
				'author' => 'Addawe, J., and Pajimola, A.K.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'THE 4TH INTERNATIONAL CONFERENCE ON QUANTITATIVE SCIENCES AND ITS APPLICATIONS (ICOQSIA 2016) AIP Conf. Proc.',
				'volume' => '1782',
				'link' => 'https://doi.org/10.1063/1.4966069',
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Optimizing Genetic Algorithm Parameters for Multiple Sequence Alignment Based on Structural Information',
				'author' => 'Sueño M.R. and Addawe J.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'Advanced Studies in Biology',
				'volume' => '8',
				'link' => 'http://dx.doi.org/10.12988/asb.2016.51250',
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'P-adic Qth Roots Via Newton-Raphson Method',
				'author' => 'Ignacio, P.S., Addawe, J., and Nable, J.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'Thai Journal of Mathematics',
				'volume' => '14',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Optimization of seasonal ARIMA models using differential evolution – simulated annealing (DESA) algorithm in forecasting dengue cases in Baguio City',
				'author' => 'Addawe, R., Addawe, J. and Magadia, J.',
				'published_date' => '2016-01-01',
				'type' => 'International',
				'journal' => 'AIP Conf. Proc.',
				'volume' => '1776',
				'link' => 'http://dx.doi.org/10.1063/1.4965385',
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Analysis of age-structured malaria transmission model',
				'author' => 'Addawe, J. and Lope, E.',
				'published_date' => '2012-01-01',
				'type' => 'National',
				'journal' => 'Philippine Science Letters',
				'volume' => '5',
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'Sensitivity analysis of age-structured malaria transmission model',
				'author' => 'Addawe, J. and Lope, E.',
				'published_date' => '2012-01-01',
				'type' => 'International',
				'journal' => 'AIP Conf. Proc.',
				'volume' => '1482',
				'link' => 'http://dx.doi.org/10.1063/1.4757437',
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'DESA: A Hybrid Optimization Algorithm for High Dimensional Functions',
				'author' => 'Addawe, R., Addawe, J, Adorio, E and Magadia, J.',
				'published_date' => '2006-05-01',
				'type' => 'International',
				'journal' => 'A publication of the International Association of Science and Technology for Development (IASTED), Proceedings of the International Conference on Control and Applications',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'title' => 'A DESA Algorithm for Parameter Estimation of Gaussians',
				'author' => 'Addawe, R., Addawe, J., Adorio, E. and Magadia, J.',
				'published_date' => '2005-05-01',
				'type' => 'National',
				'journal' => 'Proceedings of the 5th Philippine Computing Science Congress',
				'volume' => NULL,
				'link' => NULL,
				'user_id' => 3,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			],
			/* [
				'title' => '',
				'author' => '',
				'published_date' => '',
				'type' => '',
				'journal' => '',
				'volume' => '',
				'link' => '',
				'user_id' => ,
				'published_at' => now(),
				'created_at' => now(),
				'updated_at' => now(),
			], */
			
		]);
    }
}
