<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Faculty extends Model
{
	protected $table = 'faculty';

	protected $fillable = [
    'first_name',
		'middle_name',
		'last_name',
		'position',
		'bs_degree',
		'ms_degree',
		'phd_degree',
		'research_interest',
		'profile_image',		//profile_alt is autogenerated from name
		'status_id',
    ];

  public function user()
  {
      return $this->hasMany('App\Models\User', 'user_id');
  }

	public function status()
	{
		return $this->hasOne('App\Models\FacultyStatus', 'status_id', 'status_id');
	}

	public function department()
	{
		return $this->belongsTo('App\Models\Department', 'dept_id');
	}

	public function achievements()
	{
		return $this->hasOne('App\Models\OtherAchievement', 'user_id', 'user_id');
	}
}
